Enable to embed external vector graphics
veusz/veusz pull request #492
Opened 2020-12-27 10:10 UTC by korintje

This PR adds the function to import a .svg file as a vector image, not a raster image.

Veusz has powerful figure composing ability, in addition to excellent plotting functions. Therefore, I think some users will have benefit if veusz can import an external vector-based images (e.g. chemical structures) without rasterizing. The "add imagefile" function also can import .svg vector graphics, however, it rasterizes the images and sometimes makes their resolutions low.

This PR implements `SVGFile` class, which is similar to `ImageFile` class.
- The `SVGFile` instances can be added by "Add svgfile" button in the shape tools menu.
- The `SVGFile` instances are rendered by `QSvgRenderer`.
- The `SVGFile` instances are encoded into base64 data with type of `svgfile`.

The imported image can be rendered and embeded as a vector image as shown in the picture below.

![1](https://user-images.githubusercontent.com/30950088/103167140-c3e1fc80-486b-11eb-84a6-90c0e31661b4.png)

`SVGFile` is implemented separately from `ImageFile` class to keep the backward compatibility and reduce unnecessary conditional branches. The newly added code in the `veusz.widgets.shape.py` may need to become more sophisticated (many of the method in the `SVGFile` and `ImageFile` are duplicated). I left it as is so far because I am new to the code design policy of veusz (e.g. Are function overloads allowed or not?). I think there are some options. I would like to discuss how to improve it. 

I would be appreciate if you consider adding this function.

Many Thanks!
korintje

2020-12-27 11:03 UTC, korintje commented
Although I have informed that build checks at Ubuntu were unsuccessful, it seems to be not related to my file changes.
It may be derived from some dead links of libraries for Ubuntu 18.0x `apt-get` commands.

2020-12-27 12:59 UTC, jeremysanders commented
Thanks for the contribution. I'll take a look. The build is failing because I didn't have an `apt-get update` in the build commands. That should be fixed if you merge with the latest master branch.

2020-12-27 13:39 UTC, korintje commented
I have merged with the latest master branch, and checks have passed.
Thanks for the suggestion.

2020-12-29 13:01 UTC, jeremysanders commented on veusz/setting/controls.py
> +            title = _('Chose SVG file')
```suggestion
            title = _('Choose SVG file')
```

2020-12-29 13:16 UTC, jeremysanders commented on veusz/widgets/shape.py
> +            f.close()
```suggestion
            with open(s.filename, 'rb') as f:
                data = f.read()
```

2020-12-29 13:19 UTC, jeremysanders requested changes
This looks a very nice addition to the program. Thanks a lot!

I have a couple of very minor suggestions (hopefully you can see these) - there's a typo and I suggest using a with statement for reading the file.

I can fix these after merging, or feel free to make the suggested changes I've made.

Thanks again

Jeremy

2020-12-29 17:58 UTC, jeremysanders approved these changes

2020-12-29 17:59 UTC, korintje commented
Thanks for the review!
I have merged changes you suggested.

2020-12-29 17:59 UTC, merged

2020-12-29 17:59 UTC, jeremysanders commented
Thanks very much for the contribution - merged!